final Map<String, Map<String, dynamic>> regimes = {
  "Carnivore ++": {
    "emoji": "🍖",
    "desc": "Viande à chaque repas",
    "frequences": {
      "Boeuf": 7,
      "Poulet": 2,
      "Porc": 3,
      "Veau": 0.25,
      "Canard": 0.5,
      "Agneau/mouton": 0.25,
      "Poisson": 2,
      "Oeufs": 2,
      "Lait": 2,
      "Beurre": 14,
      "Laitages (crèmes, yaourts)": 2,
      "Fromage": 5,
      "De saison": 10,
      "Hors saison/non local/exotique": 2,
      "Plats cuisinés et conserves": 2,
      "Pain": 10,
      "Légumineuses": 2,
      "Pâtes, blé, couscous": 1,
      "Riz": 1,
      "Sodas, jus, sirops, etc.": 2,
      "Eau en bouteille": 1,
      "Alcool": 7,
    },
  },
  "Carnivore": {
    "emoji": "🥩",
    "desc": "Viande 1x/jour",
    "frequences": {
      "Boeuf": 5,
      "Poulet": 1,
      "Porc": 2,
      "Canard": 0.5,
      "Poisson": 1,
      "Oeufs": 2,
      "Lait": 2,
      "Beurre": 10,
      "Laitages (crèmes, yaourts)": 2,
      "Fromage": 5,
      "De saison": 10,
      "Hors saison/non local/exotique": 2,
      "Plats cuisinés et conserves": 2,
      "Pain": 10,
      "Légumineuses": 2,
      "Pâtes, blé, couscous": 1,
      "Riz": 1,
      "Sodas, jus, sirops, etc.": 2,
      "Eau en bouteille": 1,
      "Alcool": 7,
    },
  },
  "Flexitarien": {
    "emoji": "🍗",
    "desc": "Viande 3–4×/semaine",
    "frequences": {
      "Poulet": 1,
      "Porc": 1,
      "Canard": 0.5,
      "Poisson": 2,
      "Oeufs": 2,
      "Lait": 2,
      "Beurre": 7,
      "Laitages (crèmes, yaourts)": 2,
      "Fromage": 3,
      "De saison": 14,
      "Hors saison/non local/exotique": 2,
      "Plats cuisinés et conserves": 1,
      "Pain": 5,
      "Légumineuses": 4,
      "Pâtes, blé, couscous": 2,
      "Riz": 1,
      "Sodas, jus, sirops, etc.": 2,
      "Eau en bouteille": 1,
      "Alcool": 7,
    },
  },
  "Végétarien": {
    "emoji": "🥚",
    "desc": "Sans viande/poisson",
    "frequences": {
      "Oeufs": 2,
      "Lait": 2,
      "Beurre": 7,
      "Laitages (crèmes, yaourts)": 4,
      "Fromage": 3,
      "De saison": 14,
      "Hors saison/non local/exotique": 2,
      "Plats cuisinés et conserves": 1,
      "Pain": 7,
      "Légumineuses": 4,
      "Pâtes, blé, couscous": 2,
      "Riz": 1,
      "Sodas, jus, sirops, etc.": 0,
      "Eau en bouteille": 0,
      "Alcool": 3,
    },
  },
  "Végan": {
    "emoji": "🌿",
    "desc": "100% végétal",
    "frequences": {
      "De saison": 14,
      "Hors saison/non local/exotique": 0,
      "Pain": 7,
      "Légumineuses": 10,
      "Pâtes, blé, couscous": 2,
      "Riz": 2,
      "Sodas, jus, sirops, etc.": 0,
      "Eau en bouteille": 0,
      "Alcool": 3,
    },
  },
};
