final Map<String, Map<String, dynamic>> regimes = {
  "Carnivore ++": {
    "emoji": "🍖",
    "desc": "Viande à chaque repas",
    "frequences": {
      "Boeuf": 10,
      "Poulet": 4,
      "Poisson": 2,
      "Oeuf": 2,
      "Lait": 2,
      "Fromage": 2,
      "Légumes": 2,
      "Fruits": 2,
      "Céréales": 2,
      "Légumineuses": 1,
      "Produits transformés": 2,
      "Boissons sucrées": 1,
      "Snacks": 1,
      "Alcool": 1,
    },
  },
  "Carnivore": {
    "emoji": "🥩",
    "desc": "Viande 1x/jour",
    "frequences": {
      "Boeuf": 5,
      "Poulet": 3,
      "Poisson": 2,
      "Oeuf": 2,
      "Lait": 3,
      "Fromage": 2,
      "Légumes": 3,
      "Fruits": 3,
      "Céréales": 3,
      "Légumineuses": 1,
      "Produits transformés": 2,
      "Boissons sucrées": 1,
      "Snacks": 1,
      "Alcool": 1,
    },
  },
  "Flexitarien": {
    "emoji": "🍗",
    "desc": "Viande 3–4×/semaine",
    "frequences": {
      "Boeuf": 2,
      "Poulet": 2,
      "Poisson": 2,
      "Oeuf": 3,
      "Lait": 3,
      "Fromage": 2,
      "Légumes": 5,
      "Fruits": 5,
      "Céréales": 5,
      "Légumineuses": 2,
      "Produits transformés": 1,
      "Boissons sucrées": 1,
      "Snacks": 1,
      "Alcool": 1,
    },
  },
  "Végétarien": {
    "emoji": "🥚",
    "desc": "Sans viande/poisson",
    "frequences": {
      "Boeuf": 0,
      "Poulet": 0,
      "Poisson": 0,
      "Oeuf": 4,
      "Lait": 4,
      "Fromage": 3,
      "Légumes": 7,
      "Fruits": 7,
      "Céréales": 5,
      "Légumineuses": 4,
      "Produits transformés": 1,
      "Boissons sucrées": 1,
      "Snacks": 1,
      "Alcool": 1,
    },
  },
  "Végan": {
    "emoji": "🌿",
    "desc": "100% végétal",
    "frequences": {
      "Boeuf": 0,
      "Poulet": 0,
      "Poisson": 0,
      "Oeuf": 0,
      "Lait": 0,
      "Fromage": 0,
      "Légumes": 10,
      "Fruits": 10,
      "Céréales": 6,
      "Légumineuses": 5,
      "Produits transformés": 1,
      "Boissons sucrées": 1,
      "Snacks": 1,
      "Alcool": 1,
    },
  },
};
